---
title: "Deepdive plotly"
author: "christianbomholt"
date: "November 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.height = 4, fig.width = 9,dpi=90)

library(tidyverse)
library(plotly)
library(dplyr)
library(readxl)
data <- read_excel("../data/xl/udrykningsaktivitet2.xlsx")
```

## Mere syntax

- Deep dive i `plotly`
  - barcharts
  - density plots
  - faceting
  - heatmaps
  - contour
  - Animation

## Barcharts

Bemærk at `reorder` kan bruges til at få pænt sorterede barcharts. Da `Hændelsestype` er en factor får vi et barchart

```{r, echo=T}
data %>%
  group_by(Hændelsestype) %>%
  summarise(avg_time = mean(`Mandtimer i alt`)) %>% 
  mutate(Hændelsestype = fct_reorder(Hændelsestype, avg_time)) %>%  
  plot_ly(x = ~Hændelsestype, y = ~avg_time) %>% 
  layout(margin = list(l = 50, r = 50, b = 150, t = 50, pad = 4))
```


## Grouped bars

```{r}
data %>% count(Hændelsestype, `Hændelsesplacering hovedgruppe`) %>%
  mutate(Hændelsestype = fct_reorder(Hændelsestype, n)) %>% 
  plot_ly(x = ~Hændelsestype, y = ~n, color = ~`Hændelsesplacering hovedgruppe`) %>% 
  layout(margin = list(l = 50, r = 50, b = 150, t = 50, pad = 4))
```



### Histograms

```{r}
d1<- data %>% filter(`Hændelsesplacering hovedgruppe`=="Bygning")%>% select(Døgntime) %>% unlist() %>% as.numeric()
d2<- data %>% filter(`Hændelsesplacering hovedgruppe`!="Bygning")%>% select(Døgntime) %>% unlist() %>% as.numeric()

plot_ly(alpha = 0.6) %>%
  add_histogram(x = ~d1, name = "bygning") %>%
  add_histogram(x = ~d2, name = "Ikke bygning") %>%
  layout()
```


### Density plots

```{r}
(ggplot(diamonds, aes(x = price)) + 
  geom_density(aes(fill = color), alpha = 0.5) + 
  ggtitle("Kernel Density estimates by group")) %>% 
  ggplotly
```


### Anvedt på tidssøjle

```{r}
library(lubridate)
library(hms)
library(scales)

data$time <- hms::hms(second(data$Alarmmodtaget), minute(data$Alarmmodtaget), hour(data$Alarmmodtaget))  
data$time <- as.POSIXct(data$time)
ggplot(data, aes(time)) + 
  geom_density(fill = "red", alpha = 0.5) + 
  scale_x_datetime(breaks = date_breaks("2 hours"), labels=date_format("%H:%M"))
```


### subplots


```{r}
p1<-plot_ly(data, x = ~`Antal indsatte personer i alt`, y = ~`Mandtimer i alt`, type = "scatter")
p2<-plot_ly(data %>% filter(`Antal indsatte personer i alt`<50 & `Mandtimer i alt`<500), x = ~`Antal indsatte personer i alt`, y = ~`Mandtimer i alt`, type = "histogram2dcontour")

subplot(p1,p2)

```


### Automatsk multiplot

```{r}
economics %>%
  tidyr::gather(variable, value, -date) %>%
  transform(id = as.integer(factor(variable))) %>%
  plot_ly(x = ~date, y = ~value, color = ~variable, colors = "Dark2",
          yaxis = ~paste0("y", id)) %>%
  add_lines() %>%
  subplot(nrows = 5, shareX = TRUE)
```


### Faceting

```{r}
(ggplot(mpg, aes(displ, hwy))+
  geom_point()+
  stat_smooth()+
  facet_wrap(~year)) %>% 
ggplotly()
```

### Heatmaps

```{r}
# plot_ly(z = volcano, type = "heatmap")
```


### Animation

```{r}
library(gapminder)

gapminder %>%
  plot_ly(
    x = ~gdpPercap, 
    y = ~lifeExp, 
    size = ~pop, 
    color = ~continent, 
    frame = ~year, 
    text = ~country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  ) %>%
  layout(
    xaxis = list(
      type = "log"
    )
  )
```

